<script src="${base}/statics/js/easyui1.4.3/jquery.min.js" type="text/javascript"></script> 
<script src="${base}/statics/js/easyui1.4.3/jquery.easyui.min.js" type="text/javascript"></script> 
<script src="${base}/statics/js/easyui1.4.3/easyui-lang-zh_CN.js" type="text/javascript"></script> 
<script src="${base}/statics/js/jquery/jquery.dateFormat-1.0.js" type="text/javascript"></script>
<script src="${base}/statics/js/common/common.js?version=${version}" type="text/javascript"></script>
<script src="${base}/statics/js/common/MyUtil.js?version=${version}" type="text/javascript"></script>
<script src="${base}/statics/js/common/MaskUtil.js?version=${version}" type="text/javascript"></script>
<script src="${base}/statics/js/common/bulidCommonData.js?version=${version}" type="text/javascript"></script>
<script src="${base}/statics/js/common/easyUiValidate.js?version=${version}" type="text/javascript"></script>
<script type="text/javascript" src="${base}/statics/js/common/jqueryExtends.js"></script>
<#--<script type="text/javascript" src="${trackerJsUrl}"></script>-->
<script src="${base}/statics/js/jquery/ajaxfileupload.js" type="text/javascript"></script>
